### ISSUE TITLE
[Bug]When the routing policy configures Eureka, only the first registered instance will be called

### ISSUE THREAD

**Issue by LyricsYo** [SoftwareAG/webmethods-api-gateway#17]
[Bug]When the routing policy configures Eureka, only the first registered instance will be called

**Comment by carundev** [comment]
@LyricsYo Can you please elaborate on the issue. I need the following
1) Export of the API
2) Server logs after invoking the API

**Comment by vallabbharath** [comment]
@LyricsYo  I am closing this issue as there is no response for the logs requested. Please comment back or open new issue if you have the logs.
