### ISSUE TITLE
[Request] accessing application name on request/response transformation

### ISSUE THREAD

**Issue by aryell** [SoftwareAG/webmethods-api-gateway#24]
In the documentation, i can see request.authorization.clientId and request.authorization.userName.
I've tried it but it was an empty string.
Please add application name to the context of transformation.

**Comment by przemekulik** [comment]
@aryell Can you please describe your use case in more detail. Thanks

**Comment by aryell** [comment]
@przemekulik , I'm on 10.5 for API on-prem and API cloud.
The use case is to do request transformation & response transformation based on a few criteria:
1. Application name
2. Request path
3. Payload
The native endpoint itself shall be routed based on the path (context/dynamic-routing), there are 3 different native endpoint.
Payload request and response shall be transformed based on the application name (for specific consumer applications).
The payload transformation itself consist of:
1. String Concatenation, and
2. String conditional mapping, ex: resp_s := (resp_s.equals("1") || resp_s.equals("2")) ? "APPROVED" : "PENDING";

I'm able doing it using API on-prem by calling IS Service (which will call getContext to get the application name),
but I try to figure out this use case in API cloud (which unable to invoke IS Service) might adding more latency due to call external services.
I've tried the transformation using XLST but I can't go any further due to I don't know how to access the context variable (${request} and ${response}) on the XSLT.

I was thinking the XSLT additional alternative such as node.js which Integration.io have, but that's just my two cents.

**Comment by vallabbharath** [comment]
Hi @aryell ,

1) Application name support is introduced from 10.7 versions through syntax ${request.application.name} which will be rolled out to cloud post Apr 2021
2) Request path. Already accessible in 10.5 via syntax ${request.path}
3) Payload transformation without using IS Service or XSLT is possible from 10.7
3A) String concatenation works even in 10.5 versions. You just need to add two variable syntax together and it will work. 
For example; ${request.headers.header1}${request.headers.header2} will concat the values from both headers. You can also add some hardcoded value for these concatination in combination with the variables. For example: h1=${request.headers.header1};h2=${request.headers.header2}  if you want to print in the h1=val1;h2=val2 format.
3B) Can already be achieved in 10.5 via multiple Request Transformation policies to execute based on given conditions. 

Another alternative in 10.7 for usecase 3B is to define custom variables (also supported to define conditionally). You can conditionally define custom variables (assign some value to it) using "Custom Extension" policy and use the same variable across other policies (even in other stages).

Please let me know if you have any other questions. If not, can we proceed to close this issue?

Regards,
Vallab

**Comment by aryell** [comment]
Hi @vallabbharath,

Thanks for the information that we can concat the ${request} variable. It really helpful.

I'm really excited for the next 10.7 release with all those nice features.

Thank you.

**Comment by vallabbharath** [comment]
Thanks @aryell
