### ISSUE TITLE
Teams link is broken

### ISSUE THREAD

**Issue by franklin-antony** [SoftwareAG/webmethods-api-gateway#84]
@vpraveenon  - Could you please check out the the "Teams in API Gateway" link - https://tech.forums.softwareag.com/t/teams-in-apigateway Seems to be broken.

**Comment by przemekulik** [comment]
@franklin-antony Please check this https://tech.forums.softwareag.com/t/teams-in-api-gateway/237355 
Where did you get your link?

**Comment by franklin-antony** [comment]
Thanks @przemekulik

**Comment by vpraveenon** [comment]
@franklin-antony  @przemekulik  - Links are fixed now. Thanks
